00000100:00080000:0.0F:1579386058.610219:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386058.610243:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386058.610244:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386058.610246:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392068243
00000100:00080000:0.0:1579386058.610247:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 41s
00000100:00080000:0.0:1579386058.610249:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386061.615483:0:3721:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386061.615491:0:3721:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579386061.615496:0:3721:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386061.615506:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386058/real 1579386061]  req@ffff923339ce4f00 x1656006775041232/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386104 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386061.615513:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386061.615514:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386083.610174:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386083.610177:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386083.610178:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386083.610180:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392093243
00000100:00080000:0.0:1579386083.610181:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 46s
00000100:00080000:0.0:1579386083.610184:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386083.610243:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386083.610246:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386083/real 1579386083]  req@ffff923339ce5500 x1656006775041264/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386134 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386083.610252:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386083.610253:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386090.211087:0:3762:0:(pinger.c:632:ping_evictor_main()) evicting all exports of obd lustre-OST0000 older than 1579385940
00000100:02000400:0.0:1579386090.211092:0:3762:0:(pinger.c:658:ping_evictor_main()) lustre-OST0000: haven't heard from client lustre-MDT0000-mdtlov_UUID (at 10.29.161.11@tcp) in 258 seconds. I think it's dead, and I am evicting it. exp ffff92333a35a400, cur 1579386090 expire 1579385940 last 1579385832
00000100:00080000:0.0:1579386090.211097:0:3762:0:(pinger.c:660:ping_evictor_main()) Last request was at 1579385832
00000020:00080000:0.0:1579386090.211098:0:3762:0:(genops.c:1625:class_fail_export()) disconnecting export ffff92333a35a400/lustre-MDT0000-mdtlov_UUID
00000020:00000080:0.0:1579386090.211102:0:3762:0:(genops.c:1463:class_disconnect()) disconnect: cookie 0xadd338e2bc94dc5e
00000100:00080000:0.0:1579386090.211104:0:3762:0:(import.c:1650:ptlrpc_cleanup_imp()) ffff9232dabd4000 X³xÕ2’ÿÿX³xÕ2’ÿÿ: changing import state from FULL to CLOSED
00000020:00080000:0.0:1579386090.211472:0:3762:0:(genops.c:1642:class_fail_export()) disconnected export ffff92333a35a400/lustre-MDT0000-mdtlov_UUID
00000020:00000080:0.0:1579386095.396596:0:3733:0:(genops.c:987:class_export_put()) final put ffff92333a35a400/lustre-MDT0000-mdtlov_UUID
00000020:00000080:0.0:1579386095.396603:0:3711:0:(genops.c:937:class_export_destroy()) destroying export ffff92333a35a400/lustre-MDT0000-mdtlov_UUID for lustre-OST0000
00000020:00000080:0.0:1579386095.396613:0:3711:0:(genops.c:1177:class_import_destroy()) destroying import ffff9232dabd4000 for lustre-OST0000
00000100:00080000:0.0:1579386108.610460:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386108.610463:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386108.610464:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386108.610467:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392118243
00000100:00080000:0.0:1579386108.610468:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386108.610471:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386108.610504:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386108.610507:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386108/real 1579386108]  req@ffff923339ce5500 x1656006775041296/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386163 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386108.610513:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386108.610513:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386133.610314:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386133.610317:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386133.610318:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386133.610321:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392143243
00000100:00080000:0.0:1579386133.610322:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386133.610326:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386136.615580:0:3722:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386136.615590:0:3722:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579386136.615595:0:3722:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386136.615608:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386133/real 1579386136]  req@ffff923339ce5500 x1656006775041328/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386188 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386136.615615:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386136.615617:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386158.610318:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386158.610321:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386158.610322:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386158.610324:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392168243
00000100:00080000:0.0:1579386158.610325:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386158.610327:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386158.610359:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386158.610362:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386158/real 1579386158]  req@ffff923339ce4f00 x1656006775041360/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386213 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386158.610367:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386158.610368:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386183.610202:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386183.610205:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386183.610206:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386183.610218:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392193243
00000100:00080000:0.0:1579386183.610219:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386183.610223:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386183.610295:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386183.610298:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386183/real 1579386183]  req@ffff923339ce4f00 x1656006775041392/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386238 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386183.610303:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386183.610304:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386208.610345:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386208.610347:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386208.610348:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386208.610351:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392218243
00000100:00080000:0.0:1579386208.610351:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386208.610354:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386211.615722:0:3723:0:(lib-socket.c:645:lnet_sock_connect()) Error -113 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386211.615731:0:3723:0:(acceptor.c:112:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 was unreachable: the network or that node may be down, or Lustre may be misconfigured.
00000800:00000100:0.0:1579386211.615735:0:3723:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386211.615746:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386208/real 1579386211]  req@ffff923339ce4f00 x1656006775041424/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386263 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386211.615753:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386211.615754:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386233.610246:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386233.610250:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386233.610250:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386233.610253:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392243243
00000100:00080000:0.0:1579386233.610254:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386233.610258:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386233.610293:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386233.610296:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386233/real 1579386233]  req@ffff923339ce5500 x1656006775041456/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386288 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386233.610302:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386233.610303:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386258.610163:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386258.610166:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386258.610167:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386258.610169:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392268243
00000100:00080000:0.0:1579386258.610170:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386258.610172:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386258.610220:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386258.610223:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386258/real 1579386258]  req@ffff923339ce5500 x1656006775041488/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386313 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386258.610229:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386258.610230:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386283.610441:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386283.610452:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386283.610454:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386283.610463:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392293243
00000100:00080000:0.0:1579386283.610466:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386283.610473:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386283.612212:0:3720:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386283.612238:0:3720:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386283.612255:0:3720:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386283.612279:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386283/real 1579386283]  req@ffff923339ce5500 x1656006775041520/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386338 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386283.612302:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386283.612306:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386308.610438:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386308.610448:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386308.610451:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386308.610459:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392318243
00000100:00080000:0.0:1579386308.610462:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386308.610470:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386308.610559:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386308.610569:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386308/real 1579386308]  req@ffff923339ce5500 x1656006775041552/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386363 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386308.610591:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386308.610595:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386333.610334:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386333.610344:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386333.610347:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386333.610355:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392343243
00000100:00080000:0.0:1579386333.610359:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386333.610366:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386333.610503:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386333.610513:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386333/real 1579386333]  req@ffff923339ce5500 x1656006775041584/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386388 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386333.610539:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386333.610543:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386358.610447:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386358.610457:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386358.610459:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386358.610468:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392368243
00000100:00080000:0.0:1579386358.610471:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386358.610479:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386358.611561:0:3721:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386358.611588:0:3721:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386358.611600:0:3721:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386358.611624:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386358/real 1579386358]  req@ffff923339ce5500 x1656006775041616/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386413 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386358.611648:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386358.611652:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386383.610501:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386383.610511:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386383.610513:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386383.610522:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392393243
00000100:00080000:0.0:1579386383.610525:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386383.610533:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386383.610622:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386383.610632:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386383/real 1579386383]  req@ffff923339ce5500 x1656006775041648/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386438 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386383.610658:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386383.610662:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386408.610641:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386408.610651:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386408.610654:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386408.610662:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392418243
00000100:00080000:0.0:1579386408.610665:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386408.610673:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386408.610764:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386408.610774:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386408/real 1579386408]  req@ffff923339ce5500 x1656006775041680/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386463 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386408.610796:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386408.610799:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386433.610402:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386433.610412:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386433.610414:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386433.610437:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392443243
00000100:00080000:0.0:1579386433.610441:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386433.610449:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386433.611591:0:3722:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386433.611617:0:3722:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386433.611630:0:3722:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386433.611653:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386433/real 1579386433]  req@ffff923339ce5500 x1656006775041712/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386488 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386433.611681:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386433.611686:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386458.610572:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386458.610582:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386458.610584:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386458.610593:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392468243
00000100:00080000:0.0:1579386458.610597:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386458.610604:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386458.610692:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386458.610702:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386458/real 1579386458]  req@ffff923339ce5500 x1656006775041744/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386513 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386458.610724:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386458.610728:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386483.610310:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386483.610319:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386483.610322:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386483.610331:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392493243
00000100:00080000:0.0:1579386483.610334:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386483.610342:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386483.610436:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386483.610445:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386483/real 1579386483]  req@ffff923339ce5500 x1656006775041776/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386538 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386483.610468:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386483.610471:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386508.610415:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386508.610425:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386508.610427:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386508.610436:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392518243
00000100:00080000:0.0:1579386508.610439:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386508.610447:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386508.611693:0:3723:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386508.611718:0:3723:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386508.611731:0:3723:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386508.611756:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386508/real 1579386508]  req@ffff923339ce5500 x1656006775041808/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386563 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386508.611779:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386508.611783:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386533.610515:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386533.610526:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386533.610528:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386533.610537:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392543243
00000100:00080000:0.0:1579386533.610540:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386533.610547:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386533.610658:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386533.610668:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386533/real 1579386533]  req@ffff923339ce5500 x1656006775041840/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386588 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386533.610689:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386533.610693:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386558.610463:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386558.610473:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386558.610476:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386558.610485:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392568243
00000100:00080000:0.0:1579386558.610488:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386558.610496:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386558.610586:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386558.610596:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386558/real 1579386558]  req@ffff923339ce5500 x1656006775041872/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386613 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386558.610619:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386558.610622:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386583.610359:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386583.610369:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386583.610372:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386583.610381:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392593243
00000100:00080000:0.0:1579386583.610384:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386583.610392:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386583.611749:0:3720:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386583.611779:0:3720:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386583.611793:0:3720:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386583.611822:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386583/real 1579386583]  req@ffff923339ce5500 x1656006775041904/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386638 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386583.611847:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386583.611852:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386608.610610:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386608.610620:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386608.610623:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386608.610632:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392618243
00000100:00080000:0.0:1579386608.610635:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386608.610642:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386608.610750:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386608.610762:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386608/real 1579386608]  req@ffff923339ce5500 x1656006775041936/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386663 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386608.610784:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386608.610788:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386633.610363:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386633.610373:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386633.610376:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386633.610385:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392643243
00000100:00080000:0.0:1579386633.610388:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386633.610396:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386633.610481:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386633.610491:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386633/real 1579386633]  req@ffff923339ce5500 x1656006775041968/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386688 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386633.610512:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386633.610515:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386658.610363:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386658.610372:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386658.610380:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386658.610389:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392668243
00000100:00080000:0.0:1579386658.610392:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386658.610399:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386658.611567:0:3721:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386658.611593:0:3721:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386658.611606:0:3721:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386658.611630:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386658/real 1579386658]  req@ffff923339ce5500 x1656006775042000/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386713 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386658.611679:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386658.611682:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386683.610215:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386683.610224:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386683.610227:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386683.610235:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392693243
00000100:00080000:0.0:1579386683.610238:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386683.610246:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386683.610336:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386683.610347:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386683/real 1579386683]  req@ffff923339ce5500 x1656006775042032/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386738 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386683.610368:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386683.610372:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386708.610308:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386708.610318:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386708.610326:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386708.610335:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392718243
00000100:00080000:0.0:1579386708.610338:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386708.610346:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386708.610439:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386708.610449:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386708/real 1579386708]  req@ffff923339ce5500 x1656006775042064/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386763 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386708.610471:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386708.610475:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386733.610315:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386733.610325:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386733.610327:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386733.610336:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392743243
00000100:00080000:0.0:1579386733.610339:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386733.610346:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386733.611436:0:3722:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386733.611462:0:3722:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386733.611475:0:3722:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386733.611498:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386733/real 1579386733]  req@ffff923339ce5500 x1656006775042096/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386788 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386733.611521:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386733.611525:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386758.610414:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386758.610424:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386758.610431:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386758.610439:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392768243
00000100:00080000:0.0:1579386758.610443:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386758.610450:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386758.610541:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386758.610551:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386758/real 1579386758]  req@ffff923339ce5500 x1656006775042128/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386813 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386758.610574:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386758.610577:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386783.610397:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386783.610407:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386783.610410:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386783.610418:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392793243
00000100:00080000:0.0:1579386783.610422:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386783.610429:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386783.610517:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386783.610527:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386783/real 1579386783]  req@ffff923339ce5500 x1656006775042160/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386838 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386783.610549:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386783.610552:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386808.610374:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386808.610384:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386808.610387:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386808.610395:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392818243
00000100:00080000:0.0:1579386808.610399:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386808.610411:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386808.611611:0:3723:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386808.611637:0:3723:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386808.611649:0:3723:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386808.611672:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386808/real 1579386808]  req@ffff923339ce5500 x1656006775042192/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386863 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386808.611696:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386808.611700:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386833.611443:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386833.611453:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386833.611456:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386833.611464:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392843243
00000100:00080000:0.0:1579386833.611468:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386833.611475:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386833.611564:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386833.611574:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386833/real 1579386833]  req@ffff923339ce5500 x1656006775042224/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386888 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386833.611595:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386833.611598:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386858.611301:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386858.611311:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386858.611313:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386858.611322:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392868244
00000100:00080000:0.0:1579386858.611325:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386858.611337:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386858.611426:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386858.611436:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386858/real 1579386858]  req@ffff923339ce5500 x1656006775042256/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386913 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386858.611458:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386858.611461:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386883.611363:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386883.611373:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386883.611376:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386883.611384:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392893244
00000100:00080000:0.0:1579386883.611387:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386883.611394:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386883.612483:0:3720:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386883.612511:0:3720:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386883.612525:0:3720:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386883.612549:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386883/real 1579386883]  req@ffff923339ce5500 x1656006775042288/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386938 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386883.612573:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386883.612577:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386908.611418:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386908.611427:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386908.611430:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386908.611439:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392918244
00000100:00080000:0.0:1579386908.611442:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386908.611454:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386908.611544:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386908.611554:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386908/real 1579386908]  req@ffff923339ce5500 x1656006775042320/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386963 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386908.611576:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386908.611579:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386933.611509:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386933.611520:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386933.611523:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386933.611531:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392943244
00000100:00080000:0.0:1579386933.611535:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386933.611542:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386933.611634:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386933.611643:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386933/real 1579386933]  req@ffff923339ce5500 x1656006775042352/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579386988 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386933.611665:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386933.611668:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386958.611588:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386958.611598:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386958.611601:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386958.611610:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392968244
00000100:00080000:0.0:1579386958.611613:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386958.611621:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579386958.612748:0:3721:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579386958.612775:0:3721:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579386958.612792:0:3721:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579386958.612819:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386958/real 1579386958]  req@ffff923339ce5500 x1656006775042384/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387013 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386958.612844:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386958.612848:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579386983.611303:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579386983.611312:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579386983.611315:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579386983.611324:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4392993244
00000100:00080000:0.0:1579386983.611327:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579386983.611335:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579386983.611466:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579386983.611478:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579386983/real 1579386983]  req@ffff923339ce5500 x1656006775042416/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387038 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579386983.611500:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579386983.611503:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387008.611568:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387008.611578:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387008.611581:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387008.611590:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393018244
00000100:00080000:0.0:1579387008.611593:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387008.611601:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387008.611690:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387008.611700:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387008/real 1579387008]  req@ffff923339ce5500 x1656006775042448/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387063 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387008.611727:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387008.611730:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387033.611340:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387033.611350:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387033.611353:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387033.611362:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393043244
00000100:00080000:0.0:1579387033.611365:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387033.611373:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579387033.612531:0:3722:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579387033.612559:0:3722:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579387033.612573:0:3722:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579387033.612597:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387033/real 1579387033]  req@ffff923339ce5500 x1656006775042480/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387088 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387033.612621:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387033.612625:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387058.611366:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387058.611376:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387058.611378:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387058.611387:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393068244
00000100:00080000:0.0:1579387058.611390:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387058.611398:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387058.611492:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387058.611548:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387058/real 1579387058]  req@ffff923339ce5500 x1656006775042512/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387113 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387058.611576:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387058.611580:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387083.611304:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387083.611314:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387083.611317:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387083.611372:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393093244
00000100:00080000:0.0:1579387083.611375:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387083.611383:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387083.611476:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387083.611486:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387083/real 1579387083]  req@ffff923339ce5500 x1656006775042544/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387138 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387083.611509:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387083.611512:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387108.611700:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387108.611710:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387108.611713:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387108.611721:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393118244
00000100:00080000:0.0:1579387108.611724:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387108.611732:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579387108.612989:0:3723:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579387108.613017:0:3723:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579387108.613032:0:3723:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579387108.613057:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387108/real 1579387108]  req@ffff923339ce5500 x1656006775042576/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387163 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387108.613085:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387108.613089:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387133.611589:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387133.611599:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387133.611602:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387133.611611:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393143244
00000100:00080000:0.0:1579387133.611614:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387133.611621:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387133.611709:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387133.611719:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387133/real 1579387133]  req@ffff923339ce5500 x1656006775042608/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387188 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387133.611741:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387133.611744:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387158.611345:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387158.611355:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387158.611358:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387158.611366:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393168244
00000100:00080000:0.0:1579387158.611370:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387158.611377:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387158.611489:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387158.611499:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387158/real 1579387158]  req@ffff923339ce5500 x1656006775042640/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387213 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387158.611521:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387158.611524:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387183.611275:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387183.611285:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387183.611289:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387183.611297:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393193244
00000100:00080000:0.0:1579387183.611301:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387183.611308:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579387183.612545:0:3720:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579387183.612571:0:3720:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579387183.612584:0:3720:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579387183.612609:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387183/real 1579387183]  req@ffff923339ce5500 x1656006775042672/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387238 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387183.612633:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387183.612637:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387208.611276:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387208.611288:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387208.611291:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387208.611300:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393218244
00000100:00080000:0.0:1579387208.611304:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387208.611312:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387208.611411:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387208.611422:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387208/real 1579387208]  req@ffff923339ce5500 x1656006775042704/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387263 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387208.611520:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387208.611524:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387233.611308:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387233.611318:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387233.611320:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387233.611329:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393243244
00000100:00080000:0.0:1579387233.611332:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387233.611340:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387233.611431:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387233.611441:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387233/real 1579387233]  req@ffff923339ce5500 x1656006775042736/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387288 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387233.611484:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387233.611488:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387258.611866:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387258.611876:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387258.611879:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387258.611887:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393268244
00000100:00080000:0.0:1579387258.611890:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387258.611898:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579387258.613080:0:3721:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579387258.613108:0:3721:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579387258.613121:0:3721:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579387258.613147:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387258/real 1579387258]  req@ffff923339ce5500 x1656006775042768/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387313 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387258.613172:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387258.613176:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387283.611317:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387283.611327:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387283.611329:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387283.611338:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393293244
00000100:00080000:0.0:1579387283.611341:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387283.611349:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387283.611440:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387283.611450:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387283/real 1579387283]  req@ffff923339ce5500 x1656006775042800/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387338 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387283.611549:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387283.611553:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387308.611250:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387308.611260:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387308.611263:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387308.611272:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393318244
00000100:00080000:0.0:1579387308.611276:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387308.611283:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387308.611375:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387308.611385:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387308/real 1579387308]  req@ffff923339ce5500 x1656006775042832/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387363 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387308.611407:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387308.611411:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387333.611405:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387333.611416:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387333.611423:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387333.611432:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393343244
00000100:00080000:0.0:1579387333.611435:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387333.611443:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000400:00000100:0.0:1579387333.612651:0:3722:0:(lib-socket.c:645:lnet_sock_connect()) Error -111 connecting 10.29.160.166/1023 -> 10.29.161.11/988
00000400:00000100:0.0:1579387333.612679:0:3722:0:(acceptor.c:105:lnet_connect_console_error()) Connection to 10.29.161.11@tcp at host 10.29.161.11 on port 988 was refused: check that Lustre is running on that node.
00000800:00000100:0.0:1579387333.612694:0:3722:0:(socklnd_cb.c:425:ksocknal_txlist_done()) Deleting packet type 1 len 520 10.29.160.166@tcp->10.29.161.11@tcp
00000100:00000400:0.0:1579387333.612720:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387333/real 1579387333]  req@ffff923339ce5500 x1656006775042864/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387388 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387333.612745:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387333.612749:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00000100:00080000:0.0:1579387358.611414:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387358.611424:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387358.611427:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387358.611436:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393368244
00000100:00080000:0.0:1579387358.611439:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387358.611447:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00000800:00000100:0.0:1579387358.611538:0:3728:0:(socklnd_cb.c:921:ksocknal_launch_packet()) No usable routes to 12345-10.29.161.11@tcp
00000100:00000400:0.0:1579387358.611588:0:3728:0:(client.c:2116:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1579387358/real 1579387358]  req@ffff923339ce5500 x1656006775042896/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/544 e 0 to 1 dl 1579387413 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
00000100:00080000:0.0:1579387358.611610:0:3728:0:(import.c:1284:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to DISCONN
00000100:00080000:0.0:1579387358.611613:0:3728:0:(import.c:1330:ptlrpc_connect_interpret()) recovery of lustre-MDT0000_UUID on 10.29.161.11@tcp failed (-110)
00010000:00080000:0.0:1579387362.152372:0:3942:0:(ldlm_lib.c:1231:target_handle_connect()) lustre-OST0000: connection from lustre-MDT0000-mdtlov_UUID@10.29.161.11@tcp t0 exp           (null) cur 1579387362 last 0
00000020:00000080:0.0:1579387362.152434:0:3942:0:(genops.c:1379:class_connect()) connect: client lustre-MDT0000-mdtlov_UUID, cookie 0xadd338e2bc952218
00002000:00080000:0.0:1579387362.152439:0:3942:0:(ofd_obd.c:180:ofd_parse_connect_data()) lustre-OST0000: Received MDS connection for group 0
00000020:01000000:0.0:1579387362.152459:0:3942:0:(lprocfs_status_server.c:342:lprocfs_exp_setup()) using hash ffff9232d0196a80
00002000:00080000:0.0:1579387362.152461:0:3942:0:(ofd_obd.c:397:ofd_obd_connect()) lustre-OST0000: get connection from MDS 0
00000100:00080000:0.0:1579387362.152466:0:3942:0:(import.c:105:ptlrpc_import_enter_resend()) ffff9232e7583000 X³xÕ2’ÿÿX³xÕ2’ÿÿ: changing import state from NEW to RECOVER
00000100:00080000:0.0:1579387362.152469:0:3942:0:(import.c:1535:ptlrpc_import_recovery_state_machine()) ffff9232e7583000 X³xÕ2’ÿÿX³xÕ2’ÿÿ: changing import state from RECOVER to FULL
00000100:02000000:0.0:1579387362.152471:0:3942:0:(import.c:1541:ptlrpc_import_recovery_state_machine()) lustre-OST0000: Connection restored to lustre-MDT0000-mdtlov_UUID (at 10.29.161.11@tcp)
00000100:00080000:0.0:1579387383.611367:0:3731:0:(pinger.c:217:ptlrpc_pinger_process_import()) lustre-MDT0000-lwp-OST0000_UUID->lustre-MDT0000_UUID: level DISCONN/3 force 0 force_next 0 deactive 0 pingable 1 suppress 0
00000100:00080000:0.0:1579387383.611377:0:3731:0:(recover.c:58:ptlrpc_initiate_recovery()) lustre-MDT0000_UUID: starting recovery
00000100:00080000:0.0:1579387383.611380:0:3731:0:(import.c:681:ptlrpc_connect_import()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from DISCONN to CONNECTING
00000100:00080000:0.0:1579387383.611389:0:3731:0:(import.c:524:import_select_connection()) lustre-MDT0000-lwp-OST0000: connect to NID 10.29.161.11@tcp last attempt 4393393244
00000100:00080000:0.0:1579387383.611392:0:3731:0:(import.c:568:import_select_connection()) lustre-MDT0000-lwp-OST0000: tried all connections, increasing latency to 50s
00000100:00080000:0.0:1579387383.611400:0:3731:0:(import.c:602:import_select_connection()) lustre-MDT0000-lwp-OST0000: import ffff9232c2fbd800 using connection 10.29.161.11@tcp/10.29.161.11@tcp
00010000:00080000:0.0:1579387383.613141:0:3728:0:(ldlm_request.c:1329:ldlm_cli_update_pool()) @@@ Zero SLV or Limit found (SLV: 0, Limit: 91900)  req@ffff923339ce5500 x1656006775042928/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/384 e 0 to 0 dl 1579387438 ref 1 fl Rpc:RN/0/0 rc 0/0
00000100:00080000:0.0:1579387383.613163:0:3728:0:(import.c:1035:ptlrpc_connect_interpret()) lustre-MDT0000-lwp-OST0000: connect to target with instance 2
00000100:00080000:0.0:1579387383.613174:0:3728:0:(import.c:1235:ptlrpc_connect_interpret()) @@@ lustre-MDT0000-lwp-OST0000: evicting (reconnect/recover flags not set: 4)  req@ffff923339ce5500 x1656006775042928/t0(0) o38->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 520/384 e 0 to 0 dl 1579387438 ref 1 fl Interpret:RN/0/0 rc 0/0
00000100:00080000:0.0:1579387383.613188:0:3728:0:(import.c:1238:ptlrpc_connect_interpret()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from CONNECTING to EVICTED
00000100:02020000:0.0:1579387383.613193:0:3728:0:(import.c:1470:ptlrpc_import_recovery_state_machine()) 167-0: lustre-MDT0000-lwp-OST0000: This client was evicted by lustre-MDT0000; in progress operations using this service will fail.
00000100:00080000:0.0:1579387383.613210:0:3728:0:(import.c:1474:ptlrpc_import_recovery_state_machine()) evicted from lustre-MDT0000_UUID@10.29.161.11@tcp; invalidating
00000100:00080000:0.0:1579387383.613291:0:21441:0:(import.c:1416:ptlrpc_invalidate_import_thread()) thread invalidate import lustre-MDT0000-lwp-OST0000 to lustre-MDT0000_UUID@10.29.161.11@tcp
00000100:00080000:0.0:1579387383.613294:0:21441:0:(import.c:215:ptlrpc_deactivate_and_unlock_import()) setting import lustre-MDT0000_UUID INVALID
00000100:00080000:0.0:1579387383.620423:0:21441:0:(import.c:1425:ptlrpc_invalidate_import_thread()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from EVICTED to RECOVER
00000100:00080000:0.0:1579387383.620431:0:21441:0:(import.c:1535:ptlrpc_import_recovery_state_machine()) ffff9232c2fbd800 lustre-MDT0000_UUID: changing import state from RECOVER to FULL
00000100:02000000:0.0:1579387383.620439:0:21441:0:(import.c:1541:ptlrpc_import_recovery_state_machine()) lustre-MDT0000-lwp-OST0000: Connection restored to 10.29.161.11@tcp (at 10.29.161.11@tcp)
00010000:00080000:0.0:1579387408.613281:0:3729:0:(ldlm_request.c:1329:ldlm_cli_update_pool()) @@@ Zero SLV or Limit found (SLV: 0, Limit: 91900)  req@ffff923339ce4f00 x1656006775042960/t0(0) o400->lustre-MDT0000-lwp-OST0000@10.29.161.11@tcp:12/10 lens 224/192 e 0 to 0 dl 1579387415 ref 1 fl Rpc:RN/0/0 rc 0/0
00002000:00080000:0.0:1579387415.330244:0:3942:0:(ofd_dev.c:1635:ofd_create_hdl()) ofd_last_id() = 897 -> diff = -28
00002000:02000040:0.0:1579387415.330246:0:3942:0:(ofd_dev.c:1495:ofd_orphans_destroy()) lustre-OST0000: deleting orphan objects from 0x0:870 to 0x0:897
00002000:00080000:0.0:1579387415.330585:0:3942:0:(ofd_dev.c:1522:ofd_orphans_destroy()) lustre-OST0000: after destroy: set last_id to 0x0:869
00002000:00080000:0.0:1579387415.332068:0:3942:0:(ofd_dev.c:1752:ofd_create_hdl()) lustre-OST0000: reserve 8 objects in group 0x0 at 898
00002000:00080000:0.0:1579387415.332173:0:3942:0:(ofd_dev.c:1752:ofd_create_hdl()) lustre-OST0000: reserve 8 objects in group 0x0 at 906
00002000:00080000:0.0:1579387415.332226:0:3942:0:(ofd_dev.c:1752:ofd_create_hdl()) lustre-OST0000: reserve 8 objects in group 0x0 at 914
00002000:00080000:0.0:1579387415.332277:0:3942:0:(ofd_dev.c:1752:ofd_create_hdl()) lustre-OST0000: reserve 8 objects in group 0x0 at 922
